// {/* <ContainerNavbar>
// <UL className="activeNavbar">
//   <NavLink to="/" activeClassName="active" className="navbar">
//     HOME
//   </NavLink>
//   {/* <NavLink
//     exact
//     to="/services"
//     activeClassName="active"
//     className="navbar"
//   >
//     SERVICES
//   </NavLink> */}
//   {/* <NavLink exact to="/resume" activeClassName="active" className="navbar">
//     RESUMEN
//   </NavLink> */}
//   <NavLink
//     exact
//     to="/portfolio"
//     activeClassName="active"
//     className="navbar"
//   >
//     PROYECTOS
//   </NavLink>

//   <NavLink
//     exact
//     to="/contact"
//     activeClassName="active"
//     className="navbar"
//   >
//     CONTACTO
//   </NavLink>
//   {/* <NavLink exact to="/blog" activeClassName="active" className="navbar">
//     MI BLOG
//   </NavLink> */}
// </UL>
// <div className="Burguer">
//   {/* agregamos el boton burguer */}
//   <BurguerButton />
// </div>
// </ContainerNavbar>
// );
// };

// const ContainerNavbar = styled.div`
// display: flex;
// justify-content: center;
// align-items: center;

// .Burguer {
// @media (min-width: 768px) {
// display: none;
// }
// }
// `;

// const UL = styled.ul`
// display: flex;
// justify-content: center;
// font-weight: bold;
// position: absolute;
// top: -700px;
// left: 2000px;
// margin-left: auto;
// margin-right: auto;

// .navbar {
// display: block;
// }
// .activeNavbar {
// width: 100%;
// display: block;
// position: absolute;
// margin-left: auto;
// margin-right: auto;
// top: 30%;
// left: 0;
// right: 0;
// text-align: center;
// }

// @media (min-width: 768px) {
// display: none;
// }
// `;

// export default Navbar; */}
